### ISSUE TITLE
Consideration for Q-Digest type?

### ISSUE THREAD

**Issue by robskillington** [RichiH/OpenMetrics#67]
Would like to get some feedback on if the format would accommodate describing Q-Digest metric types. 

As Q-Digests are mergeable we've had success (albeit experimentally) merging aggregate Q-Digests across thousands of hosts for a single aggregation window and seen promising results for this data type.  We then convert to user specified quartiles and store those.

The advantage as an alternative to histograms is that no bucket selection needs to be made up front and the accuracy looks to be quite high.

This disadvantage as an alternative to histograms is that unless you store them in the storage layer they cannot be merged later with other series (unlike histograms which you can just add together).

I believe the case is compelling to support the data type so users can choose whether they want flexibility for emitting (Q-Digest) vs flexibility at query time (Histograms).

**Comment by xichen2020** [comment]
In terms of summary-based data structures / algorithms, [t-digest](https://github.com/tdunning/t-digest) is claimed to be mergeable and orders of magnitude more accurate than q-digest with smaller summaries . It also supports floating point numbers, while q-digest only supports integers.

**Comment by brian-brazil** [comment]
There's two problems with Q-Digests/T-Digests.

Firstly they can't be sanely represented as time series, as they are mutating trees. We need things that are numbers and use labels sanely so that they can be of use and not blow-out storage for the TSDB on the other end.

Secondly you can't calculate a quantile over an arbitrary time frame like you can with a Histogram, the instrumentation library has to pre-choose the time frame and you need it to be consistent across all clients.

An additional disadvantage is that you can't pre-specify buckets. Many SLAs are written in the form 99% latency below 500ms, and people focus on the 99% rather than the 500ms. For an accurate answer as to how you're doing on your SLA you need a Histogram with a 500ms bucket.

For general background see https://github.com/prometheus/prometheus/issues/2682

**Comment by beorn7** [comment]
I disagree with the first point as it's merely a deficiency of the current Prometheus implementation to only have a single floating point number as a value in a time series. Such a limitation should not leak into OpenMetrics.

I agree with the second point, though. The ability to calculate quantiles over arbitrary time frames is a helpful and very fundamental feature of Prometheus (rather than a limitation). See https://github.com/prometheus/prometheus/issues/2682#issuecomment-299844923 for details.

The third point is more a digression. In a situation where a fixed threshold like 500ms already exist (per SLO etc.), pre-defined buckets are indeed handy (also see http://www.apdex.org/ ). However, we are talking about situations where it is annoying to be forced to pre-define buckets, precisely because those fixed thresholds don't exist or are not in the focus if interest.

**Comment by brian-brazil** [comment]
> It's merely a deficiency of the current Prometheus implementation to only have a single floating point number as a value in a time series

Prometheus is not the only thing that might be on the other end, and as monitoring systems go we're already on the sophisticated side of things. Consider this data ending up in Graphite for example, where this would be an even more severe performance issue. I'd also hope for something that 100% works with the Prometheus of today, not a potential future Prometheus.

I'm partially using Prometheus as a stand-in for other monitoring systems. I would like to avoid having multiple overlapping types which require every single implementation on the other end to efficiently implement a myriad of different distribution types in order to cover all the potential use cases. Do we really need to have all the 5-6 distribution types mentioned so far? Can Summary/Histogram cover enough uses cases to be good enough?

I propose that we only accept types that are at least some way useful if the other end doesn't have first class type support as many many monitoring systems don't have such support. Neither will ad-hoc tools built to work with the format. For example even without the `histogram_quantile` function in Prometheus, a Histograms' buckets can still be treated as counters and graphed usefully. The Summary's quantiles can be graphed directly. That's not the case for any of the proposed digests/sketches.

A format where monitoring systems in common use have to drop a non-trivial proportion of the metrics due to not being able to support them and also have to keep that blacklist up to date isn't a great format. I'd like a format where we're forward compatible, so if a new type is added that systems that don't explicitly support it can still get something useful out of it.

**Comment by robskillington** [comment]
I'm not advocating monitoring systems actually store Q-Digests.  We have the distinct use case, as do some others, for aggregating and calculating quartiles across a number of hosts without predefining buckets and then storing the quartiles.  

Using Q-Digest in this manner is very similar to Summaries in Prometheus with the sole difference being the quartile calculation occurs by the monitoring system and as such means it can calculate an accurate quartile from readings across a large set of instances before storing calculated quartile values.

> I propose that we only accept types that are at least some way useful if the other end doesn't have first class type support as many many monitoring systems don't have such support. Neither will ad-hoc tools built to work with the format. For example even without the histogram_quantile function in Prometheus, a Histograms' buckets can still be treated as counters and graphed usefully. The Summary's quantiles can be graphed directly. That's not the case for any of the proposed digests/sketches.

If you are exposing Q-Digest's at an exposition format, a naive system can very simply calculate the quartiles and store the quartile values.  Adhoc tools are very simple to write to support this use case.

> Can Summary/Histogram cover enough uses cases to be good enough?

That's really the crux of the problem, we have seen very frequently that users outside of the Histogram use case want to monitor things not necessarily for SLA purposes and truly do want to just define quartiles that are accurate across multiple instances.  

For instance "how long does my ML training job run for".  Defining buckets for a task that can take anywhere between 5 minutes to 5 hours becomes very tedious.  If the job suddenly takes 3x longer due to a code change you need to go update the Histogram buckets again.  If you're doing this over multiple machines Summaries starts to become a lot less useful.

The only way to achieve this is either collecting all raw samples from all instances and aggregating in a single place, or using Q-Digest and then letting a monitoring system merge them and store the quartile values.

**Comment by brian-brazil** [comment]
> If you are exposing Q-Digest's at an exposition format, a naive system can very simply calculate the quartiles and store the quartile values. Adhoc tools are very simple to write to support this use case.

I disagree that that's simple. That requires both first-class type support in the ingesting system and the ability to then do calculations across that data over time - something that I believe most monitoring systems lack. That implicitly also requires that monitoring systems store the Q/T-Digests.

This is the general issue I'm trying to point out, if we let in this class of thing it makes it much harder to implement as a monitoring system and practically speaking greatly restricts the class of monitoring system that can deal with it and may leads us back to the problems of vendor-specific "variations" we see with SNMP.

> Defining buckets for a task that can take anywhere between 5 minutes to 5 hours becomes very tedious.

If something is taking that long, we're getting into the areas where metrics break down. Event logging is a better solution when we're into moderately long running batch tasks. We can actually manage this form of infrequent event logging with Prometheus via the pushgateway.

> using Q-Digest and then letting a monitoring system merge them and store the quartile values.

If the data is over days, the question of what time period we're measuring the quantile over becomes even more important. The Prometheus Summary for example only does it over ~10m.

**Comment by robskillington** [comment]
Closing this in favor of talking about support for metric aggregation in #69
